import { useEffect, useState } from 'react'
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material'
import type { RfqItem } from '../rfqs/rfqItemRepository'
import type { SourcingCandidate } from './sourcingComparison'
import { cancelSourcingDecision, selectSourcingCandidate, subscribeSourcingDecisions, subscribeSourcingState, type SourcingDecision } from './sourcingCallableRepository'

const quantityText = (millis: number) => (millis / 1000).toLocaleString('ja-JP', { maximumFractionDigits: 3 })
export function SourcingDecisionPanel({ rfqId, item, candidates }: { rfqId: string; item: RfqItem; candidates: SourcingCandidate[] }) {
  const [state, setState] = useState(0), [decisions, setDecisions] = useState<SourcingDecision[]>([]), [open, setOpen] = useState(false), [candidateId, setCandidateId] = useState(''), [quantity, setQuantity] = useState(''), [shipping, setShipping] = useState('0'), [reason, setReason] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => subscribeSourcingState(rfqId, item.id, value => setState(value.selectedQuantityMillis), () => setError('採用数量を取得できませんでした。')), [rfqId, item.id])
  useEffect(() => subscribeSourcingDecisions(rfqId, item.id, setDecisions, () => setError('採用履歴を取得できませんでした。')), [rfqId, item.id])
  const remaining = Math.max(0, item.quantity * 1000 - state)
  const selected = candidates.find(value => value.id === candidateId) ?? candidates[0]
  const begin = () => { setCandidateId(candidates[0]?.id ?? ''); setQuantity(quantityText(remaining)); setShipping(String(candidates[0]?.shippingFee ?? 0)); setReason(''); setError(''); setOpen(true) }
  const save = async () => { if (!selected) return; setBusy(true); setError(''); try { await selectSourcingCandidate(rfqId, item.id, selected, Number(quantity), Number(shipping), reason); setOpen(false) } catch (cause) { setError(cause instanceof Error ? cause.message : '採用に失敗しました。') } finally { setBusy(false) } }
  const cancel = async (decision: SourcingDecision) => { setBusy(true); setError(''); try { await cancelSourcingDecision(rfqId, item.id, decision.id) } catch (cause) { setError(cause instanceof Error ? cause.message : '採用解除に失敗しました。') } finally { setBusy(false) } }
  return <Stack spacing={1} sx={{ mt: 2 }}><Alert severity={remaining === 0 ? 'success' : 'info'}>採用済み: {quantityText(state)} {item.unit} ／ 未採用: {quantityText(remaining)} {item.unit}</Alert>{error && <Alert severity="error">{error}</Alert>}<Button variant="contained" onClick={begin} disabled={remaining === 0 || candidates.length === 0}>購入先を採用</Button>{decisions.filter(value => value.status === 'active').map(value => <Stack key={value.id} direction="row" spacing={2} alignItems="center"><Typography>{value.source}: {value.selectedQuantity} {item.unit}（送料込 {value.totalCost.toLocaleString('ja-JP')}円）</Typography><Button size="small" color="warning" disabled={busy} onClick={() => void cancel(value)}>採用解除</Button></Stack>)}<Dialog open={open} onClose={() => !busy && setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>購入先を採用</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField select label="候補" value={selected?.id ?? ''} onChange={event => { const next = candidates.find(value => value.id === event.target.value); setCandidateId(event.target.value); setShipping(String(next?.shippingFee ?? 0)) }}>{candidates.map(value => <MenuItem key={value.id} value={value.id}>{value.source} / {value.seller || '—'} / {value.itemName}</MenuItem>)}</TextField><TextField label="採用数量" type="number" value={quantity} onChange={event => setQuantity(event.target.value)} helperText={`未採用数量: ${quantityText(remaining)} ${item.unit}`} /><TextField label="この採用数量での送料（円）" type="number" value={shipping} onChange={event => setShipping(event.target.value)} /><TextField label="理由・確認内容" multiline minRows={2} value={reason} onChange={event => setReason(event.target.value)} helperText={selected?.expired ? '期限切れ候補のため入力必須です。' : '期限・在庫などの確認内容を記録できます。'} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)} disabled={busy}>取消</Button><Button variant="contained" onClick={() => void save()} disabled={busy || !selected}>採用を保存</Button></DialogActions></Dialog></Stack>
}
