import { useRef, useState, type FormEvent } from 'react'
import { Alert, Box, Button, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material'
import { RFQ_STATUSES, rfqSchema, rfqStatusLabels } from './rfqSchema'
import { type Rfq, type RfqCustomer, type RfqInput } from './rfqRepository'
export function RfqForm({ rfq, customers, onSave, onCancel, error }: { rfq: Rfq | null; customers: RfqCustomer[]; onSave: (input: RfqInput, customerName: string) => Promise<void>; onCancel: () => void; error: string | null }) {
  const [input, setInput] = useState<RfqInput>(rfq ? { customerId: rfq.customerId, subject: rfq.subject, receivedAt: rfq.receivedAt?.toDate().toISOString().slice(0, 10) ?? '', dueDate: rfq.dueDate?.toDate().toISOString().slice(0, 10) ?? '', requestedDeliveryDate: rfq.requestedDeliveryDate?.toDate().toISOString().slice(0, 10) ?? '', status: rfq.status, assignedUserId: rfq.assignedUserId, note: rfq.note } : { customerId: '', subject: '', receivedAt: new Date().toISOString().slice(0, 10), dueDate: '', requestedDeliveryDate: '', status: 'received', assignedUserId: '', note: '' })
  const [validationError, setValidationError] = useState<string | null>(null), [busy, setBusy] = useState(false); const submitting = useRef(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting.current) return; const result = rfqSchema.safeParse(input); if (!result.success) { setValidationError(result.error.issues[0].message); return }; const customer = customers.find(item => item.id === result.data.customerId); if (!customer) { setValidationError('顧客を選択してください。'); return }; submitting.current = true; setBusy(true); setValidationError(null); try { await onSave(result.data, customer.name) } finally { submitting.current = false; setBusy(false) } }
  const availableCustomers = customers.filter(customer => customer.active || customer.id === input.customerId)
  return <Paper component="form" onSubmit={event => void submit(event)} sx={{ maxWidth: 800, mx: 'auto', p: { xs: 2, md: 3 } }}><Stack spacing={2}><Box><Typography component="h1" variant="h4">{rfq ? 'RFQ案件を編集' : 'RFQ案件を登録'}</Typography><Typography color="text.secondary">案件番号は保存時に自動採番されます。</Typography></Box>{(error || validationError) && <Alert severity="error">{error || validationError}</Alert>}<TextField select required label="顧客" value={input.customerId} disabled={busy} onChange={event => setInput(current => ({ ...current, customerId: event.target.value }))}>{availableCustomers.map(customer => <MenuItem key={customer.id} value={customer.id} disabled={!customer.active}>{customer.name}{customer.active ? '' : '（無効）'}</MenuItem>)}</TextField><TextField required autoFocus label="件名" value={input.subject} disabled={busy} slotProps={{ htmlInput: { maxLength: 500 } }} onChange={event => setInput(current => ({ ...current, subject: event.target.value }))} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required fullWidth label="見積依頼受信日" type="date" slotProps={{ inputLabel: { shrink: true } }} value={input.receivedAt} disabled={busy} onChange={event => setInput(current => ({ ...current, receivedAt: event.target.value }))} /><TextField fullWidth label="見積期限" type="date" slotProps={{ inputLabel: { shrink: true } }} value={input.dueDate} disabled={busy} onChange={event => setInput(current => ({ ...current, dueDate: event.target.value }))} /></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="希望納期" type="date" slotProps={{ inputLabel: { shrink: true } }} value={input.requestedDeliveryDate} disabled={busy} onChange={event => setInput(current => ({ ...current, requestedDeliveryDate: event.target.value }))} /><TextField select fullWidth label="ステータス" value={input.status} disabled={busy} onChange={event => setInput(current => ({ ...current, status: event.target.value as RfqInput['status'] }))}>{RFQ_STATUSES.map(status => <MenuItem key={status} value={status}>{rfqStatusLabels[status]}</MenuItem>)}</TextField></Stack><TextField label="担当者ID" helperText="未入力でも保存できます。" value={input.assignedUserId} disabled={busy} slotProps={{ htmlInput: { maxLength: 128 } }} onChange={event => setInput(current => ({ ...current, assignedUserId: event.target.value }))} /><TextField label="備考" multiline minRows={3} value={input.note} disabled={busy} slotProps={{ htmlInput: { maxLength: 5000 } }} onChange={event => setInput(current => ({ ...current, note: event.target.value }))} /><Stack direction="row" spacing={1} justifyContent="flex-end"><Button disabled={busy} onClick={onCancel}>キャンセル</Button><Button type="submit" variant="contained" disabled={busy || customers.length === 0}>{busy ? '保存中…' : '保存'}</Button></Stack></Stack></Paper>
}
