import { Timestamp, collection, doc, getDoc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc, type Unsubscribe } from 'firebase/firestore'
import { firebaseAuth, firestore } from '../../firebase/firebase'
import { rfqSchema, type RfqStatus } from './rfqSchema'
export interface RfqInput { customerId: string; subject: string; receivedAt: string; dueDate: string; requestedDeliveryDate: string; status: RfqStatus; assignedUserId: string; note: string }
export interface RfqDocument extends Omit<RfqInput, 'receivedAt' | 'dueDate' | 'requestedDeliveryDate'> { rfqNumber: string; customerName: string; receivedAt: Timestamp | null; dueDate: Timestamp | null; requestedDeliveryDate: Timestamp | null; createdAt: Timestamp | null; createdBy: string; updatedAt: Timestamp | null; updatedBy: string }
export interface Rfq extends RfqDocument { id: string }
export interface RfqCustomer { id: string; name: string; active: boolean }
const rfqsCollection = collection(firestore, 'rfqs'); const asText = (value: unknown): string => typeof value === 'string' ? value : ''; const asTimestamp = (value: unknown): Timestamp | null => value instanceof Timestamp ? value : null; const toTimestamp = (value: string): Timestamp | null => value ? Timestamp.fromDate(new Date(`${value}T00:00:00`)) : null
function readRfq(id: string, data: Record<string, unknown>): Rfq { return { id, rfqNumber: asText(data.rfqNumber), customerId: asText(data.customerId), customerName: asText(data.customerName), subject: asText(data.subject), receivedAt: asTimestamp(data.receivedAt), dueDate: asTimestamp(data.dueDate), requestedDeliveryDate: asTimestamp(data.requestedDeliveryDate), status: asText(data.status) as RfqStatus, assignedUserId: asText(data.assignedUserId), note: asText(data.note), createdAt: asTimestamp(data.createdAt), createdBy: asText(data.createdBy), updatedAt: asTimestamp(data.updatedAt), updatedBy: asText(data.updatedBy) } }
export function subscribeRfqs(onChange: (rfqs: Rfq[]) => void, onError: (error: Error) => void): Unsubscribe { return onSnapshot(query(rfqsCollection, orderBy('receivedAt', 'desc')), snapshot => onChange(snapshot.docs.map(item => readRfq(item.id, item.data()))), onError) }
export async function getRfq(id: string): Promise<Rfq | null> { const snapshot = await getDoc(doc(firestore, 'rfqs', id)); return snapshot.exists() ? readRfq(snapshot.id, snapshot.data()) : null }
export function subscribeRfqCustomers(onChange: (customers: RfqCustomer[]) => void, onError: (error: Error) => void): Unsubscribe { return onSnapshot(query(collection(firestore, 'customers'), orderBy('name')), snapshot => onChange(snapshot.docs.map(item => ({ id: item.id, name: asText(item.data().name), active: item.data().active !== false }))), onError) }
function toDocument(input: RfqInput, customerName: string) { const parsed = rfqSchema.parse(input); return { ...parsed, customerName, receivedAt: toTimestamp(parsed.receivedAt), dueDate: toTimestamp(parsed.dueDate), requestedDeliveryDate: toTimestamp(parsed.requestedDeliveryDate) } }
export async function createRfq(input: RfqInput, customerName: string): Promise<string> { const userId = firebaseAuth.currentUser?.uid; if (!userId) throw new Error('認証情報がありません。'); const payload = toDocument(input, customerName); const year = input.receivedAt.slice(0, 4); const rfqRef = doc(rfqsCollection); const counterRef = doc(firestore, 'rfqCounters', year); await runTransaction(firestore, async transaction => { const counter = await transaction.get(counterRef); const nextSequence = counter.exists() && typeof counter.data().nextSequence === 'number' ? counter.data().nextSequence + 1 : 1; transaction.set(counterRef, { year, nextSequence, updatedAt: serverTimestamp() }); transaction.set(rfqRef, { ...payload, rfqNumber: `RFQ-${year}-${String(nextSequence).padStart(6, '0')}`, createdAt: serverTimestamp(), createdBy: userId, updatedAt: serverTimestamp(), updatedBy: userId }) }); return rfqRef.id }
export async function updateRfq(id: string, input: RfqInput, customerName: string): Promise<void> { const userId = firebaseAuth.currentUser?.uid; if (!userId) throw new Error('認証情報がありません。'); await updateDoc(doc(firestore, 'rfqs', id), { ...toDocument(input, customerName), updatedAt: serverTimestamp(), updatedBy: userId }) }
