import { Timestamp, addDoc, collection, doc, getDoc, onSnapshot, query, serverTimestamp, where, type Unsubscribe } from 'firebase/firestore'
import { firebaseAuth, firestore } from '../../firebase/firebase'
import { calculateLine } from '../supplierQuotes/quoteMoney'
import { marketplaceOfferSchema, type MarketplaceOfferInput, type MarketplaceSource } from './marketplaceOfferSchema'

export interface MarketplaceOfferDocument extends Omit<MarketplaceOfferInput, 'estimatedDeliveryDate' | 'retrievedAt' | 'itemUrl'> { rfqId: string; productId: string | null; unit: string; quantityMillis: number; subtotal: number | null; tax: number | null; total: number | null; shippingTotal: number | null; totalPrice: number | null; estimatedDeliveryDate: Timestamp | null; itemUrl: string | null; retrievedAt: Timestamp; createdAt: Timestamp | null; createdBy: string }
export interface MarketplaceOffer extends MarketplaceOfferDocument { id: string }
const text = (value: unknown) => typeof value === 'string' ? value : ''
const number = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : 0
const nullableNumber = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : null
const timestamp = (value: unknown) => value instanceof Timestamp ? value : null
export const sourceLabel: Record<MarketplaceSource, string> = { amazon: 'Amazon', rakuten: '楽天', other: 'その他' }
function read(id: string, data: Record<string, unknown>): MarketplaceOffer { return { id, rfqId: text(data.rfqId), rfqItemId: text(data.rfqItemId), source: text(data.source) as MarketplaceSource, externalItemId: text(data.externalItemId), sellerName: text(data.sellerName), itemName: text(data.itemName), partNumber: text(data.partNumber), quantity: number(data.quantity), unitPrice: number(data.unitPrice), shippingFee: nullableNumber(data.shippingFee), taxCategory: text(data.taxCategory) as MarketplaceOfferInput['taxCategory'], taxRateBps: number(data.taxRateBps), shippingTaxCategory: text(data.shippingTaxCategory) as MarketplaceOfferInput['shippingTaxCategory'], shippingTaxRateBps: number(data.shippingTaxRateBps), stockStatus: text(data.stockStatus), estimatedDeliveryDate: timestamp(data.estimatedDeliveryDate), itemUrl: typeof data.itemUrl === 'string' ? data.itemUrl : null, retrievedAt: timestamp(data.retrievedAt) ?? Timestamp.now(), note: text(data.note), productId: typeof data.productId === 'string' ? data.productId : null, unit: text(data.unit), quantityMillis: number(data.quantityMillis), subtotal: nullableNumber(data.subtotal), tax: nullableNumber(data.tax), total: nullableNumber(data.total), shippingTotal: nullableNumber(data.shippingTotal), totalPrice: nullableNumber(data.totalPrice), createdAt: timestamp(data.createdAt), createdBy: text(data.createdBy) } }
export function subscribeMarketplaceOffers(rfqId: string, changed: (offers: MarketplaceOffer[]) => void, failed: (error: Error) => void): Unsubscribe { return onSnapshot(query(collection(firestore, 'marketplaceOffers'), where('rfqId', '==', rfqId)), snapshot => changed(snapshot.docs.map(value => read(value.id, value.data())).sort((a, b) => b.retrievedAt.toMillis() - a.retrievedAt.toMillis())), failed) }
export async function createMarketplaceOffer(rfqId: string, input: MarketplaceOfferInput): Promise<void> { const uid = firebaseAuth.currentUser?.uid; if (!uid) throw new Error('ログイン状態を確認してください。'); const value = marketplaceOfferSchema.parse(input); const item = await getDoc(doc(firestore, 'rfqs', rfqId, 'items', value.rfqItemId)); if (!item.exists() || item.data().archivedAt != null || item.data().status === 'cancelled') throw new Error('案件品目が変更または削除されています。再読込してください。'); const known = value.shippingFee !== null; const amounts = calculateLine({ quantity: value.quantity, unitPrice: value.unitPrice, shippingFee: value.shippingFee ?? 0, taxCategory: value.taxCategory, taxRateBps: value.taxRateBps, shippingTaxCategory: value.shippingTaxCategory, shippingTaxRateBps: value.shippingTaxRateBps }); await addDoc(collection(firestore, 'marketplaceOffers'), { ...value, rfqId, productId: item.data().productId || null, unit: item.data().unit, quantityMillis: amounts.quantityMillis, estimatedDeliveryDate: value.estimatedDeliveryDate ? Timestamp.fromDate(new Date(`${value.estimatedDeliveryDate}T00:00:00+09:00`)) : null, itemUrl: value.itemUrl || null, retrievedAt: Timestamp.fromDate(new Date(value.retrievedAt)), subtotal: known ? amounts.subtotal : null, tax: known ? amounts.tax : null, total: known ? amounts.total : null, shippingTotal: known ? amounts.shippingTotal : null, totalPrice: known ? amounts.total : null, createdAt: serverTimestamp(), createdBy: uid }) }
