import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { FirebaseError } from 'firebase/app'
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { archiveCustomer, createCustomer, restoreCustomer, subscribeCustomers, updateCustomer, type Customer, type CustomerInput } from './customerRepository'
import { customerSchema } from './customerSchema'
import { includesSearchText, normalizeSearchText } from '../../utils/searchText'

const emptyInput: CustomerInput = { name: '', contactName: '', email: '', phone: '', postalCode: '', address: '', notes: '' }
const customerError = (error: unknown): string => error instanceof FirebaseError && error.code === 'permission-denied' ? '顧客情報へのアクセス権限がありません。Firestore Security Rulesを確認してください。' : '顧客情報の処理に失敗しました。通信状況を確認して再度お試しください。'

function CustomerDialog({ customer, onClose, onSaved }: { customer: Customer | null; onClose: () => void; onSaved: (message: string) => void }) {
  const [input, setInput] = useState<CustomerInput>(customer ? { name: customer.name, contactName: customer.contactName, email: customer.email, phone: customer.phone, postalCode: customer.postalCode, address: customer.address, notes: customer.notes } : emptyInput)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { setInput(customer ? { name: customer.name, contactName: customer.contactName, email: customer.email, phone: customer.phone, postalCode: customer.postalCode, address: customer.address, notes: customer.notes } : emptyInput); setError(null) }, [customer])
  const setField = (field: keyof CustomerInput, value: string) => setInput((current) => ({ ...current, [field]: value }))
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const result = customerSchema.safeParse(input)
    if (!result.success) { setError(result.error.issues[0].message); return }
    setBusy(true); setError(null)
    try { if (customer) { await updateCustomer(customer.id, result.data); onSaved('顧客情報を更新しました。') } else { await createCustomer(result.data); onSaved('顧客を登録しました。') } } catch (cause: unknown) { setError(customerError(cause)) } finally { setBusy(false) }
  }
  return <Dialog open onClose={busy ? undefined : onClose} fullWidth maxWidth="sm"><Box component="form" onSubmit={(event) => void save(event)}><DialogTitle>{customer ? '顧客を編集' : '顧客を登録'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}<TextField label="顧客名" required autoFocus fullWidth value={input.name} disabled={busy} onChange={(event) => setField('name', event.target.value)} /><TextField label="担当者名" fullWidth value={input.contactName} disabled={busy} onChange={(event) => setField('contactName', event.target.value)} /><TextField label="メールアドレス" type="email" fullWidth value={input.email} disabled={busy} onChange={(event) => setField('email', event.target.value)} /><TextField label="電話番号" fullWidth value={input.phone} disabled={busy} onChange={(event) => setField('phone', event.target.value)} /><TextField label="郵便番号" fullWidth value={input.postalCode} disabled={busy} onChange={(event) => setField('postalCode', event.target.value)} /><TextField label="住所" fullWidth multiline minRows={2} value={input.address} disabled={busy} onChange={(event) => setField('address', event.target.value)} /><TextField label="備考" fullWidth multiline minRows={2} value={input.notes} disabled={busy} onChange={(event) => setField('notes', event.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={busy}>キャンセル</Button><Button type="submit" variant="contained" disabled={busy}>{busy ? '保存中…' : '保存'}</Button></DialogActions></Box></Dialog>
}

export function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [search, setSearch] = useState(''), [includeInactive, setIncludeInactive] = useState(false), [editing, setEditing] = useState<Customer | null | undefined>(undefined), [busyId, setBusyId] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null)
  useEffect(() => subscribeCustomers((nextCustomers) => { setCustomers(nextCustomers); setLoading(false) }, (cause) => { setError(customerError(cause)); setLoading(false) }), [])
  const visibleCustomers = useMemo(() => { const keyword = normalizeSearchText(search); return customers.filter((customer) => (includeInactive || customer.active) && (!keyword || [customer.name, customer.contactName, customer.email, customer.phone, customer.postalCode, customer.address, customer.notes].some((value) => includesSearchText(value, keyword)))) }, [customers, includeInactive, search])
  async function toggleActive(customer: Customer) { setBusyId(customer.id); try { if (customer.active) { await archiveCustomer(customer.id); setNotice('顧客を無効にしました。') } else { await restoreCustomer(customer.id); setNotice('顧客を有効に戻しました。') } } catch (cause: unknown) { setError(customerError(cause)) } finally { setBusyId(null) } }
  return <Box sx={{ maxWidth: 1280, mx: 'auto', p: { xs: 2, md: 3 } }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} justifyContent="space-between" alignItems={{ sm: 'center' }} sx={{ mb: 3 }}><Box><Typography component="h1" variant="h4">顧客</Typography><Typography color="text.secondary">RFQで使用する顧客マスターを管理します。</Typography></Box><Button variant="contained" onClick={() => setEditing(null)}>顧客を登録</Button></Stack><Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="検索" placeholder="顧客名、担当者、連絡先、住所、備考で検索" value={search} onChange={(event) => setSearch(event.target.value)} fullWidth /><Button variant={includeInactive ? 'contained' : 'outlined'} onClick={() => setIncludeInactive((value) => !value)}>{includeInactive ? '無効な顧客を表示中' : '無効な顧客を非表示'}</Button></Stack></Paper>{error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError(null)}>{error}</Alert>}<TableContainer component={Paper}>{loading ? <Box sx={{ display: 'grid', minHeight: 220, placeItems: 'center' }}><CircularProgress aria-label="顧客一覧を読み込み中" /></Box> : <Table aria-label="顧客一覧" sx={{ minWidth: 760 }}><TableHead><TableRow><TableCell>顧客名</TableCell><TableCell>担当者</TableCell><TableCell>メールアドレス</TableCell><TableCell>電話番号</TableCell><TableCell>状態</TableCell><TableCell align="right">操作</TableCell></TableRow></TableHead><TableBody>{visibleCustomers.length === 0 ? <TableRow><TableCell colSpan={6} align="center" sx={{ py: 6, color: 'text.secondary' }}>該当する顧客はありません。</TableCell></TableRow> : visibleCustomers.map((customer) => <TableRow key={customer.id} hover><TableCell>{customer.name}</TableCell><TableCell>{customer.contactName || '—'}</TableCell><TableCell>{customer.email || '—'}</TableCell><TableCell>{customer.phone || '—'}</TableCell><TableCell><Chip size="small" color={customer.active ? 'success' : 'default'} label={customer.active ? '有効' : '無効'} /></TableCell><TableCell align="right"><Button size="small" onClick={() => setEditing(customer)} disabled={busyId === customer.id}>編集</Button><Button size="small" color={customer.active ? 'warning' : 'success'} onClick={() => void toggleActive(customer)} disabled={busyId === customer.id}>{busyId === customer.id ? '処理中…' : customer.active ? '無効化' : '有効化'}</Button></TableCell></TableRow>)}</TableBody></Table>}</TableContainer>{editing !== undefined && <CustomerDialog customer={editing} onClose={() => setEditing(undefined)} onSaved={(message) => { setEditing(undefined); setNotice(message) }} />}<Snackbar open={notice !== null} autoHideDuration={4000} onClose={() => setNotice(null)} message={notice} /></Box>
}
