import { useEffect, useRef, useState, type FormEvent } from 'react'
import { Alert, Box, Button, Checkbox, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Paper, Snackbar, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { subscribeSuppliers, type Supplier } from '../suppliers/supplierRepository'
import { subscribeRfqItems, type RfqItem } from '../rfqs/rfqItemRepository'
import { localDateInput } from '../rfqs/rfqItemSchema'
import { createSupplierQuoteRequest, subscribeSupplierQuoteRequests, updateSupplierQuoteRequest, type SupplierQuoteRequest, type SupplierQuoteRequestInput } from './supplierQuoteRequestRepository'
import { supplierQuoteRequestSchema, supplierQuoteRequestStatusLabels, type SupplierQuoteRequestStatus } from './supplierQuoteRequestSchema'
const dateText = (value: { toDate(): Date } | null) => value?.toDate().toLocaleDateString('ja-JP') ?? '—'
const empty: SupplierQuoteRequestInput = { supplierId: '', supplierName: '', rfqItemIds: [], requestedAt: '', responseDueDate: '', status: 'draft', note: '' }
const message = '仕入先見積依頼の処理に失敗しました。再度お試しください。'
function Editor({ rfqId, value, suppliers, items, close, saved }: { rfqId: string; value: SupplierQuoteRequest | null; suppliers: Supplier[]; items: RfqItem[]; close: () => void; saved: (message: string) => void }) {
  const [input, setInput] = useState<SupplierQuoteRequestInput>(value ? { supplierId: value.supplierId, supplierName: value.supplierName, rfqItemIds: value.rfqItemIds, requestedAt: value.requestedAt ? localDateInput(value.requestedAt.toDate()) : '', responseDueDate: value.responseDueDate ? localDateInput(value.responseDueDate.toDate()) : '', status: value.status, note: value.note } : empty)
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [showAllItems, setShowAllItems] = useState(false); const submitting = useRef(false); const active = items.filter(item => !item.archivedAt); const visibleItems = showAllItems ? active : active.slice(0, 8)
  async function save(event: FormEvent) { event.preventDefault(); if (submitting.current) return; const parsed = supplierQuoteRequestSchema.safeParse(input); if (!parsed.success) { setError(parsed.error.issues[0].message); return }; submitting.current = true; setBusy(true); setError(null); try { if (value) await updateSupplierQuoteRequest(rfqId, value.id, parsed.data); else await createSupplierQuoteRequest(rfqId, parsed.data); saved(value ? '仕入先見積依頼を更新しました。' : '仕入先見積依頼を登録しました。') } catch { setError(message) } finally { submitting.current = false; setBusy(false) } }
  return <Dialog open fullWidth maxWidth="sm" onClose={busy ? undefined : close}><Box component="form" onSubmit={event => void save(event)}><DialogTitle>{value ? '仕入先見積依頼を編集' : '仕入先見積依頼を登録'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}<TextField select required label="仕入先" value={input.supplierId} disabled={busy} onChange={event => { const supplier = suppliers.find(item => item.id === event.target.value); setInput(current => ({ ...current, supplierId: supplier?.id ?? '', supplierName: supplier?.name ?? '' })) }}>{suppliers.filter(supplier => supplier.active).map(supplier => <MenuItem key={supplier.id} value={supplier.id}>{supplier.name}</MenuItem>)}</TextField><Box><Typography variant="subtitle2">対象品目（{input.rfqItemIds.length}/30件）</Typography>{visibleItems.map(item => <FormControlLabel key={item.id} control={<Checkbox checked={input.rfqItemIds.includes(item.id)} disabled={busy || (!input.rfqItemIds.includes(item.id) && input.rfqItemIds.length >= 30)} onChange={event => setInput(current => ({ ...current, rfqItemIds: event.target.checked ? [...current.rfqItemIds, item.id] : current.rfqItemIds.filter(id => id !== item.id) }))} />} label={`No. ${item.lineNo} — ${item.originalDescription}`} />)}{active.length > 8 && !showAllItems && <Button disabled={busy} onClick={() => setShowAllItems(true)}>＋ 残り{active.length - 8}件を表示</Button>}</Box><TextField label="依頼日" type="date" value={input.requestedAt} disabled={busy} slotProps={{ inputLabel: { shrink: true } }} onChange={event => setInput(current => ({ ...current, requestedAt: event.target.value }))} /><TextField label="回答期限" type="date" value={input.responseDueDate} disabled={busy} slotProps={{ inputLabel: { shrink: true } }} onChange={event => setInput(current => ({ ...current, responseDueDate: event.target.value }))} /><TextField select label="状態" value={input.status} disabled={busy} onChange={event => setInput(current => ({ ...current, status: event.target.value as SupplierQuoteRequestStatus }))}>{Object.entries(supplierQuoteRequestStatusLabels).map(([key, label]) => <MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField><TextField label="備考" multiline minRows={3} value={input.note} disabled={busy} slotProps={{ htmlInput: { maxLength: 5000 } }} onChange={event => setInput(current => ({ ...current, note: event.target.value }))} /></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={close}>キャンセル</Button><Button type="submit" variant="contained" disabled={busy || active.length === 0}>{busy ? '保存中…' : '保存'}</Button></DialogActions></Box></Dialog>
}
export function SupplierQuoteRequestsSection({ rfqId }: { rfqId: string }) {
  const [requests, setRequests] = useState<SupplierQuoteRequest[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [items, setItems] = useState<RfqItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<SupplierQuoteRequest | null | undefined>(); const [notice, setNotice] = useState<string | null>(null)
  useEffect(() => subscribeSupplierQuoteRequests(rfqId, next => { setRequests(next); setLoading(false); setError(null) }, () => { setError(message); setLoading(false) }), [rfqId])
  useEffect(() => subscribeSuppliers(setSuppliers, () => setError(message)), []); useEffect(() => subscribeRfqItems(rfqId, setItems, () => setError(message)), [rfqId])
  return <Box sx={{ mt: 3 }}><Stack direction="row" justifyContent="space-between" sx={{ mb: 2 }}><Typography component="h2" variant="h5">仕入先見積依頼</Typography><Button variant="contained" disabled={loading} onClick={() => setEditing(null)}>依頼を登録</Button></Stack><Typography color="text.secondary" sx={{ mb: 2 }}>依頼内容を手動で記録します。メールは送信しません。</Typography>{error ? <Alert severity="error">{error}</Alert> : loading ? <CircularProgress /> : <TableContainer component={Paper}><Table><TableHead><TableRow>{['仕入先', '対象品目', '依頼日', '回答期限', '状態', '操作'].map(label => <TableCell key={label}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{requests.length === 0 ? <TableRow><TableCell colSpan={6} align="center">登録済みの依頼はありません。</TableCell></TableRow> : requests.map(request => <TableRow key={request.id}><TableCell>{request.supplierName}</TableCell><TableCell>{request.rfqItemIds.map(id => items.find(item => item.id === id)).filter(Boolean).map(item => `No. ${item?.lineNo}`).join(', ') || '—'}</TableCell><TableCell>{dateText(request.requestedAt)}</TableCell><TableCell>{dateText(request.responseDueDate)}</TableCell><TableCell><Chip size="small" label={supplierQuoteRequestStatusLabels[request.status] ?? request.status} /></TableCell><TableCell><Button onClick={() => setEditing(request)}>編集</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>}{editing !== undefined && <Editor key={editing?.id ?? 'new'} rfqId={rfqId} value={editing} suppliers={suppliers} items={items} close={() => setEditing(undefined)} saved={next => { setEditing(undefined); setNotice(next) }} />}<Snackbar open={Boolean(notice)} message={notice} autoHideDuration={4000} onClose={() => setNotice(null)} /></Box>
}
