import { useRef, useState, type FormEvent } from 'react'
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField } from '@mui/material'
import { createProduct, updateProduct, type Product, type ProductInput } from './productRepository'
import { productError } from './productError'
import { productSchema } from './productSchema'

const emptyInput: ProductInput = { manufacturerName: '', partNumber: '', name: '', janCode: '', category: '', unit: '個', notes: '' }
const fields: { key: keyof ProductInput; label: string; maxLength: number }[] = [{ key: 'manufacturerName', label: 'メーカー名', maxLength: 200 }, { key: 'partNumber', label: '品番', maxLength: 200 }, { key: 'name', label: '正式商品名', maxLength: 500 }, { key: 'janCode', label: 'JANコード', maxLength: 13 }, { key: 'category', label: 'カテゴリ', maxLength: 200 }, { key: 'unit', label: '標準単位', maxLength: 50 }, { key: 'notes', label: '備考', maxLength: 5000 }]
export function ProductDialog({ product, onClose, onSaved }: { product: Product | null; onClose: () => void; onSaved: (message: string) => void }) {
  const [input, setInput] = useState<ProductInput>(product ? { manufacturerName: product.manufacturerName, partNumber: product.partNumber, name: product.name, janCode: product.janCode, category: product.category, unit: product.unit, notes: product.notes } : emptyInput)
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const submitting = useRef(false)
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting.current) return; const result = productSchema.safeParse(input); if (!result.success) { setError(result.error.issues[0].message); return }; submitting.current = true; setBusy(true); setError(null); try { if (product) await updateProduct(product.id, result.data); else await createProduct(result.data); onSaved(product ? '商品情報を更新しました。' : '商品を登録しました。') } catch (cause: unknown) { setError(productError(cause)) } finally { submitting.current = false; setBusy(false) } }
  return <Dialog open onClose={busy ? undefined : onClose} fullWidth maxWidth="sm"><Box component="form" onSubmit={event => void save(event)}><DialogTitle>{product ? '商品を編集' : '商品を登録'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}{fields.map(({ key, label, maxLength }) => <TextField key={key} label={label} required={key === 'manufacturerName' || key === 'partNumber' || key === 'name' || key === 'unit'} autoFocus={key === 'manufacturerName'} fullWidth multiline={key === 'notes'} minRows={key === 'notes' ? 2 : undefined} slotProps={{ htmlInput: { maxLength } }} value={input[key]} disabled={busy} onChange={event => setInput(current => ({ ...current, [key]: event.target.value }))} />)}</Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={busy}>キャンセル</Button><Button type="submit" variant="contained" disabled={busy}>{busy ? '保存中…' : '保存'}</Button></DialogActions></Box></Dialog>
}
